//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midwife_v._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Visits = new HashSet<Visit>();
        }
    
        public int Client_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Street_NO_ { get; set; }
        public string Street_Name { get; set; }
        public string Subburb { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Post_Code { get; set; }
        public string Ethnicity { get; set; }
        public string Children { get; set; }
        public string Email { get; set; }
        public string Land_Line { get; set; }
        public string Cell_Phone { get; set; }
        public string First_Name_P { get; set; }
        public string Last_Name_P { get; set; }
        public string Street_NO__P { get; set; }
        public string Street_Name_P { get; set; }
        public string Subburb_P { get; set; }
        public string City_P { get; set; }
        public string State_P { get; set; }
        public string Post_Code_P { get; set; }
        public string Land_Line_P { get; set; }
        public string Cell_Phone_P { get; set; }
        public string First_Name_E { get; set; }
        public string Last_Name_E { get; set; }
        public string Street_NO__E { get; set; }
        public string Street_Name_E { get; set; }
        public string Subburb_E { get; set; }
        public string City_E { get; set; }
        public string State_E { get; set; }
        public string Post_Code_E { get; set; }
        public string Land_Line_E { get; set; }
        public string Cell_Phone_E { get; set; }
        public string Sex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
