//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midwife_v._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Visit_ID { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Client_ID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
